version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATABASE=amazon
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local